%\VignetteIndexEntry{The qsmooth user's guide}
%\VignettePackage{qsmooth}
%\VignetteEngine{knitr::knitr}
\documentclass{article}

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
    BiocStyle::latex()
@

\setlength{\parskip}{1\baselineskip}
\setlength{\parindent}{0pt}

\title{The \texttt{qsmooth} user's guide}
\author{Stephanie C. Hicks \texttt{stephaniechicks@gmail.com} \and
Kwame Okrah \texttt{okrah.kwame@gene.com} \and
Hector Corrado Bravo \texttt{hcorrada@gmail.com} \and
Rafael A. Irizarry \texttt{rairizarry@gmail.com} }

\date{Modified: August 4, 2015.  Compiled: \today}

\begin{document}

\maketitle
 
\tableofcontents

\section{Introduction}

Global normalization methods such as quantile normalization 
\cite{Bolstad2003, Irizarry2003} have become a standard part of the
analysis pipeline for high-throughput data to remove unwanted 
technical variation. These methods and others that rely solely 
on observed data without external information (e.g. spike-ins)
are based on the assumption that only a minority of genes are 
expected to be differentially expressed (or that an equivalent 
number of genes increase and decrease across biological conditions
\cite{aanes2014normalization}). This assumption can be interepreted
in different ways leading to different global normalization 
procedures. For example, in one normalization procedure, the method assumes
the mean expression level across genes should be the same across samples
\cite{Robinson2010}. In contrast, quantile normalization assumes the 
only difference between the statistical distribution of each sample
is technical variation. Normalization is achieved by forcing the 
observed distributions to be the same and the average distribution, 
obtained by taking the average of each quantile across samples,
is used as the reference \cite{Bolstad2003}.

While these assumptions may be reasonable in certain experiments,
they may not always be appropriate \cite{Loven2012, Hicks2015}.
For example, mRNA content has been shown to fluctuate significantly
during zebrafish early developmental stages \cite{aanes2014normalization}.
Similarily, cells expressing high levels of c-Myc undergo
transcriptional amplification causing a 2 to 3 fold change in global
gene expression compared to cells expressiong low c-Myc
\cite{Loven2012}. 

Recently, an R/Biocoductor package (\texttt{quantro}) \cite{Hicks2015} 
has been developed to test for global differences between groups of 
distributions to asses whether global normalization methods such 
as quantile normalization should be applied. If global differences
are found between groups of distributions, these changes may be of technical 
or biological of interest. If these changes are of technical interest
(e.g. batch effects), then global normalization methods should be applied. 
If these changes are related to a biological factor (e.g. normal/tumor or 
two tissues), then global normalization methods should not be applied 
because the methods will remove the interesting biological variation 
(i.e. differentially expressed genes) and artifically induce differences 
between genes that were not differentially expressed. In the cases 
with global differences between groups of distributions 
between biological conditions, quantile normalization is
not an appropriate normalization method. In
these cases, we can consider a more relaxed assumption about the data, 
namely that the statistical distribution of each sample should be the 
same within biological conditions or groups (compared to the more 
stringent assumption of quantile normalization, which states the 
statistical distribution is the same across all samples).

In this vignette we introduce a generalization of quantile 
normalization, referred to as \textbf{smooth quantile normalization} 
(\texttt{\bf{qsmooth}}), which is a weighted average of the two 
types of assumptions about the data. The \texttt{qsmooth} R-package
contains the \texttt{qsmooth()} function, which computes a weight at 
every quantile that compares the variability between groups relative 
to within groups. In one extreme, quantile normalization is applied
and in the other extreme quantile normalization within each 
biological condition is applied. The weight shrinks the group-level 
quantile normalized data towards the overall reference quantiles 
if variability between groups is sufficiently smaller than the 
variability within groups. The algorithm is described in 
Figure \ref{algo} below.

Let \texttt{gene(g)} denote the ${g}^{th}$ row after sorting 
each column in the data. For each row, \texttt{gene(g)}, we 
compute the weight $w_{(g)} \in [0, 1]$, where a weight of 0 implies 
quantile normalization within groups is applied and
a weight of 1 indicates quantile normalization is applied.
The weight at each row depends on the between group sum of squares
$\hbox{SSB}_{(g)}$ and total sum of squares $\hbox{SST}_{(g)}$,
as follows:
\begin{equation}
w_{(g)} = \hbox{median} \{1 - \hbox{SSB}_{(i)} / \hbox{SST}_{(i)} | ~i = g-k, \dots, g, \dots, g+k \},
\end{equation}
where $k=$ floor(Total number of genes * 0.05). The number 
0.05 is a flexible parameter that can be altered to change the 
window of the number of genes considered. In this way, we 
can use a rolling median to borrow information from 
neighboring genes in the weight.

\begin{figure}[!h]
\begin{center}
\includegraphics[width=\columnwidth]{qsmooth_algo.pdf}
\end{center}
\small\normalsize
\caption[qsmooth algorithm]
         {{\bf The qsmooth algorithm}}
\label{algo}
\end{figure}


\section{Getting Started}

Load the package in R
<<load-lib, message=FALSE>>=
library(qsmooth)
@


\section{Data} 

The \texttt{\bf{bodymapRat}} package contains an 
\texttt{ExpressionSet} of 652 RNA-Seq samples from a comprehensive 
rat transcriptomic BodyMap study. This data was derived from
the raw FASTQ files obtained from Yu et al. (2014) \cite{Yu2014}. 
It contains expression levels from 11 organs in male and female
rats at 4 developmental stages. We will use a subset of this 
data in this vignette.

The R-package bodymapRat can be installed from GitHub using the R package 
\texttt{\bf{devtools}}.

<<load-bodymapRat, message=FALSE, eval= FALSE>>=
library(devtools)
install_github("stephaniehicks/bodymapRat")
@


\subsection{bodymapRat Example 1 - Comparing male and female rats in one tissue}

The first example is based a dataset
which contains lung samples from 21 week old male and female rats. 
Four samples are from males and four samples are from females.

<<data-1, message=FALSE>>=
library(Biobase)
library(bodymapRat)
data(bodymapRat)

# select lung samples, stage 21 weeks, and only bio reps
keepColumns = (pData(bodymapRat)$organ == "Lung") &  
    (pData(bodymapRat)$stage == 21) & (pData(bodymapRat)$techRep == 1)
keepRows = rowMeans(exprs(bodymapRat)) > 10 # Filter out low counts
bodymapRatE1 <- bodymapRat[keepRows,keepColumns]
bodymapRatE1
@

\subsection{bodymapRat Example 2 - Comparing two tissues}

The second example is based a dataset which contains brain and liver 
tissue samples from 21 week old male and female rats. 
eight samples are from males and eight samples are from females.

<<data-2, message=FALSE>>=
# select brain and liver samples, stage 21 weeks, and only bio reps
keepColumns = (pData(bodymapRat)$organ %in% c("Brain", "Liver")) & 
         (pData(bodymapRat)$stage == 21) & (pData(bodymapRat)$techRep == 1)
keepRows = rowMeans(exprs(bodymapRat)) > 10 # Filter out low counts
bodymapRatE2 <- bodymapRat[keepRows,keepColumns]
bodymapRatE2
@

\section{Using the \texttt{qsmooth() function}}


\subsection{Input for \texttt{qsmooth()}}
The \texttt{qsmooth()} function must have two objects as input: 

\begin{itemize}
\item \texttt{object}: a data frame or matrix with observations 
(e.g. probes or genes) on the rows and samples as the columns. 
\texttt{qsmooth()} can accept objects that inherit \texttt{eSets} 
such as an \texttt{ExpressionSet} or \texttt{MethylSet}. In this case, 
the \texttt{groupFactor} must still be provided. 

\item \texttt{groupFactor}: a factor variable that represents 
the group level information about each sample. For example if the 
samples represent two different tissues, provide \texttt{qsmooth()} 
with a factor representing which columns in the \texttt{object} 
are different tissue samples.

\item \texttt{normFactors}: {\bf optional} scaling normalization factors. 
Default is \texttt{NULL}. If \texttt{normFactors} is not equal to 
\texttt{NULL}, the user can provide a vector of scaling factors 
that will be used to modify the expression data set prior to 
applying the \texttt{qsmooth} algorithm.

\item \texttt{window}: window size for running median (defined as a 
fraction of the number of rows of exprs. Default is 0.05
\end{itemize}



\subsection{Running \texttt{qsmooth()}}

\subsubsection{Using Example 1 data}
In the first example, the groups we are interested in comparing are 
contained in the \texttt{sex} column in the \texttt{pData(bodymapRatE1)} 
dataset. To run the \texttt{qsmooth()} function, input the data object 
and the object containing the phenotypic data. Here we use the 
\texttt{bodymapRatE1} data set as an example. 

The first row shows the boxplots and density plot of the raw data that
has been transformed on the \texttt{log2()} scale and added a 
pseudo-count of 1 (i.e. \texttt{log2(counts+1)}).

The second row shows the boxplots and density plot of the qsmooth 
normalized data. 

<<calculate-qsmooth1>>=
library(quantro)

par(mfrow=c(2,2))
pd1 <- pData(bodymapRatE1)
eset1_ercc <- exprs(bodymapRatE1)[grepl("^ERCC", rownames( exprs(bodymapRatE1))), ]
eset1 <- exprs(bodymapRatE1)[!grepl("^ERCC", rownames( exprs(bodymapRatE1))), ]

matboxplot(log2(eset1+1), groupFactor = pd1$sex, main = "Raw data", 
           ylab = "Expression (log2 scale)", xaxt="n")
axis(1, at=seq_len(length(pd1$sex)), labels=FALSE)
text(seq_len(length(pd1$sex)), par("usr")[3] -1, labels = pd1$sex, srt = 90, pos = 1, xpd = TRUE)

matdensity(log2(eset1+1), groupFactor = pd1$sex, main = "Raw data", 
           xlab = "Expression (log2 scale)", ylab = "density")
legend('topright', levels(factor(pd1$sex)), col = 1:2, lty = 1)

qsNormE1 <- qsmooth(object = eset1, groupFactor = pd1$sex)
matboxplot(log2(qsmoothData(qsNormE1)+1), groupFactor = pd1$sex, 
           main = "qsmooth normalized data", ylab = "Expression (log2 scale)",
           xaxt="n")
axis(1, at=seq_len(length(pd1$sex)), labels=FALSE)
text(seq_len(length(pd1$sex)), par("usr")[3] -1, labels = pd1$sex, srt = 90, pos = 1, xpd = TRUE)
matdensity(log2(qsmoothData(qsNormE1)+1), groupFactor = pd1$sex, 
           main = "qsmooth normalized data", 
           xlab = "Expression (log2 scale)", ylab = "density")
legend('topright', levels(factor(pd1$sex)), col = 1:2, lty = 1)
@

The smoothed quantile normalized data can be extracted using the 
\texttt{qsmoothData()} function (see above) and the smoothed quantile weights 
can plotted using the \texttt{qsmoothPlotWeights()} function (see below). 

<<plot-qsmooth1-weights, fig.width=4, fig.height=4>>=
qsmoothPlotWeights(qsNormE1)
@

The weights are calculated for each quantile in the data set.
A weight of 1 indicates quantile normalization is applied,
where as a weight of 0 indicates quantile normalization
within the groups is applied. See Figure \ref{algo} for 
more details on the weights.

In this example, the weights are close to 1 across all the 
quantiles indicating that there is no major difference 
between the group-level quantiles in the female and male rats. 
Here, the \texttt{qsmooth()} normalization method returns a 
normalized data set that is nearly identical
to the conventional quantile normalization. 


\subsubsection{Using Example 2 data}

In the second example (\texttt{bodymapRatE2}), the groups we 
are interested in comparing are the two types of tissues in 
the 21 week old male and female rats. 

Similar to the first example, the first row shows the boxplots 
and density plot of the raw data that has been transformed on 
the \texttt{log2()} scale and added a pseudo-count of 1 
(i.e. \texttt{log2(counts+1)}). The second row shows the boxplots 
and density plot of the qsmooth normalized data. 

<<calculate-qsmooth2>>=
par(mfrow=c(2,2))
pd2 <- pData(bodymapRatE2)
eset2_ercc <- exprs(bodymapRatE2)[grepl("^ERCC", rownames( exprs(bodymapRatE2))), ]
eset2 <- exprs(bodymapRatE2)[!grepl("^ERCC", rownames( exprs(bodymapRatE2))), ]
pd2$group <- paste(pd2$organ, pd2$sex, sep="_")

matboxplot(log2(eset2+1), groupFactor = factor(pd2$organ), main = "Raw data", 
           ylab = "Expression (log2 scale)", xaxt="n")
axis(1, at=seq_len(length(as.character(pd2$organ))), labels=FALSE)
text(seq_len(length(pd2$organ)), par("usr")[3] -2, labels = pd2$organ, srt = 90, pos = 1, xpd = TRUE)
matdensity(log2(eset2+1), groupFactor = pd2$organ, main = "Raw data", 
           xlab = "Expression (log2 scale)", ylab= "density")
legend('topright', levels(factor(pd2$organ)), col = 1:2, lty = 1)

qsNormE2 <- qsmooth(object = eset2, groupFactor = pd2$organ)
matboxplot(log2(qsmoothData(qsNormE2)+1), groupFactor = pd2$organ, 
           main = "qsmooth normalized data", ylab = "Expression (log2 scale)", 
           xaxt="n")
axis(1, at=seq_len(length(pd2$organ)), labels=FALSE)
text(seq_len(length(pd2$organ)), par("usr")[3] -2, labels = pd2$organ, srt = 90, pos = 1, xpd = TRUE)
matdensity(log2(qsmoothData(qsNormE2)+1), groupFactor = pd2$organ, 
           main = "qsmooth normalized data", 
           xlab = "Expression (log2 scale)", ylab = "density")
legend('topright', levels(factor(pd2$organ)), col = 1:2, lty = 1)
@

We see there are global differences in the distributions between the 
two tissues (liver and brain) in the rats. 

The smoothed quantile normalized data can be extracted using the 
\texttt{qsmoothData()} function (see above) and the smoothed quantile weights 
can plotted using the \texttt{qsmoothPlotWeights()} function (see below). 

<<plot-qsmooth2-weights, fig.width=4, fig.height=4>>=
qsmoothPlotWeights(qsNormE2)
@

Recall, a weight of 1 indicates quantile normalization is applied,
where as a weight of 0 indicates quantile normalization
within the groups is applied. 

In this example, the weights range from 0.2 to 0.8 across the quantiles, 
where the weights are close to 0.2 for the quantiles close to 0 and the 
weights are close to 0.8 for the quantiles close to 1. 
This plot suggests the distributions contain more variablity between
the groups compared to within groups for the small quantiles (and 
the conventional quantile normalization is not necessarily appropriate). 
As the quantiles get bigger, there is less variability between groups which 
increases the weight closer to 0.8 as the quantiles get bigger. 


\section{SessionInfo}

<<sessionInfo,results ='markup'>>=
sessionInfo()
@

\bibliography{qsmoothRef}

\end{document}